name: $(image)-$(Date:yyyyMMdd)-$(Rev:r)

trigger: 
  batch: true
  branches:
    include:
    - 'refs/tags/jenkins-inbound-agent*'
    - '*'
  paths:
    include:
    - 'jenkins-inbound-agent/*'
    exclude:
    - '*'
pr:
  branches:
    include:
    - '*'
  paths:
      include:
      - 'jenkins-inbound-agent/*'
      exclude:
      - '*'

schedules:
- cron: "30 21 1-7,15-21 * 1"
  displayName: Daily midnight build
  branches:
    include:
      - 'refs/tags/jenkins-inbound-agent*'
  always: true

variables:
  - group: build
  - name: image
    value: jenkins-inbound-agent

pool:
  name: Default

resources:
- repo: self

jobs:
  - job: Build
    displayName: Docler Build
    workspace:
      clean: all
    steps:
      - template: template/docker-build-template.yml
  - job: Push
    displayName: Docker Push
    steps:
      - template: template/docker-push-template.yml
    dependsOn: Build
    condition: and(contains(variables['build.sourceBranch'], 'refs/tags'), succeeded())
