name: $(image)-$(Date:yyyyMMdd)-$(Rev:r)

trigger: 
  batch: true
  branches:
    include:
    - 'refs/tags/nginx*'
    - '*'
  paths:
    include:
    - 'nginx/*'
    exclude:
    - '*'
pr:
  branches:
    include:
    - '*'
  paths:
      include:
      - 'nginx/*'
      exclude:
      - '*'

variables:
  - group: build
  - name: image
    value: nginx

pool:
  name: Default

resources:
- repo: self

jobs:
  - job: Build
    displayName: Docler Build
    workspace:
      clean: all
    steps:
      - template: template/docker-build-template.yml
  - job: Push
    displayName: Docker Push
    steps:
      - template: template/docker-push-template.yml
    dependsOn: Build
    condition: and(contains(variables['build.sourceBranch'], 'refs/tags'), succeeded())
